### ISSUE TITLE
Test the demo locally

### ISSUE THREAD

**Issue by Uspectacle** [handtracking-io/yoha#15]
First of all, I'm a big fan of your project.
I want to try and understand it even thought I lack most basic knowledge regarding HTML, JavaScript and TypeScript.

Using VS Code, I opened demo\draw\index.htlm with Live Server.
The result on my browser don't show any picture nor camera, only text.

Could you please give me or redirect me to a brief tutorial on how to test your demo locally ?

Thanks you in advance

**Comment by b-3-n** [comment]
Thank you for your feedback and for creating this issue.

I added a [section](https://github.com/handtracking-io/yoha#run-demo-locally) in the README to address this question as it may be interesting for others as well. 

Please re-open if you consider your matter has not been addressed completely.
