### ISSUE TITLE
local demo question

### ISSUE THREAD

**Issue by Trueman1997** [handtracking-io/yoha#16]
I want to run the demo locally,and I followed your suggestions.then the question happended:
 
(base)MacBook-Pro ~ % git clone https://github.com/handtracking-io/yoha && \
cd yoha && \
yarn && \
yarn start

Cloning into 'yoha'...
remote: Enumerating objects: 303, done.
remote: Counting objects: 100% (303/303), done.
remote: Compressing objects: 100% (180/180), done.
remote: Total 303 (delta 129), reused 273 (delta 109), pack-reused 0
Receiving objects: 100% (303/303), 13.28 MiB | 78.00 KiB/s, done.
Resolving deltas: 100% (129/129), done.
zsh: command not found: yarn

**Comment by b-3-n** [comment]
Thank you for creating this issue.

You need to install `yarn` which is a package manager (similar to `npm` in case you are familiar with it).

To do that I recommend following the official installation instructions here: https://classic.yarnpkg.com/lang/en/docs/install

Closing this issue. Feel free to re-open if you feel your concern has not been fully addressed. Alternatively, feel free to ping me on slack.
